---
- hosts: web*
  vars:
    http_port: 80
    max_clients: 200
    remote_user: vagrant
  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
    become: yes
  # - name: write the apache config file
  #   become: yes
  #   template: src=/srv/httpd.j2 dest=/etc/httpd.conf
  #   notify:
  # - restart apache
  # - name: ensure apache is running (and enable it at boot)
  #   service: name=httpd state=started enabled=yes
  # handlers:
  #   - name: restart apache
  #     service: name=httpd state=restarted

- hosts: nginx
  tasks:
  - name: demonstrate nginx configuration
    apt: name=nginx state=latest
    become: yes

...
